#!/bin/bash

set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/../.."

pulumi destroy -y

if [[ ! -z $HASURA_PRODUCTION ]]; then
  KEYPATH="$ROOT/config/keys/$HASURA_STACK_NAME"
  rm -f $KEYPATH
  rm -f $KEYPATH.pub
fi