#!/bin/bash

set -euo pipefail

export PULUMI_SKIP_UPDATE_CHECK=1

## NB: We do this because of a bug in Terraform's PostgreSQL provider - it doesn't give enough
## time for our newly created PostgreSQL instance to boot up before trying to connect to it and
## create the database and doesn't have any kind of retry logic. So, it'll barf out here with
## a connection error. We'll wait a hot second, then run `pulumi up` again.
pulumi up -y || true
sleep 3

pulumi refresh -y && pulumi up -y