#!/bin/bash

set -euo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/.."

pushd $ROOT
npm i
popd

. $ROOT/script/lib/parse-opts.sh

$ROOT/$HASURA_SCRIPT_PREFIX/bootstrap

. $ROOT/script/env.sh

$ROOT/script/update-config
npx sequelize db:migrate

$ROOT/script/import-metadata
