#!/bin/bash

set -euo pipefail

export PULUMI_SKIP_UPDATE_CHECK=1

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/.."

pushd $ROOT
npm i

## NB: pipenv is fucked on WSL2
if [ ! -f /etc/wsl.conf ]; then
  pipenv install
fi
popd

. $ROOT/script/lib/parse-opts.sh

$ROOT/$HASURA_SCRIPT_PREFIX/bootstrap

sleep 5
eval `$ROOT/script/env.sh`

sleep 5
$ROOT/script/hasura migrate apply
