#!/bin/bash

set -euo pipefail

export PULUMI_SKIP_UPDATE_CHECK=1

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/.."

. $ROOT/script/lib/parse-opts.sh

$ROOT/$HASURA_SCRIPT_PREFIX/destroy