#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const cfg = require('../config/index.js');

fs.writeFileSync(
  path.resolve(__dirname, '..', 'config', 'config.json'),
  JSON.stringify(cfg, null, 2));